apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oikotie-scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oikotie-scraper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "oikotie-scraper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "oikotie-scraper.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oikotie-scraper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.app.gracefulShutdownTimeout }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.app.environment | quote }}
            - name: DEPLOYMENT_TYPE
              value: {{ .Values.app.deploymentType | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.app.logLevel | quote }}
            - name: MAX_WORKERS
              value: {{ .Values.app.maxWorkers | quote }}
            - name: HEADLESS_BROWSER
              value: {{ .Values.app.headlessBrowser | quote }}
            - name: HEALTH_CHECK_ENABLED
              value: {{ .Values.app.healthCheckEnabled | quote }}
            - name: DATABASE_PATH
              value: {{ .Values.app.database.path | quote }}
            - name: CLUSTER_COORDINATION_ENABLED
              value: "true"
            {{- if .Values.redis.enabled }}
            - name: REDIS_URL
              value: "redis://{{ include "oikotie-scraper.redis.fullname" . }}:6379"
            {{- else if .Values.externalRedis.host }}
            - name: REDIS_URL
              value: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}"
            {{- end }}
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- with .Values.env.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: health
              containerPort: 8080
              protocol: TCP
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: /shared
            - name: logs
              mountPath: /logs
            - name: config
              mountPath: /app/config
              readOnly: true
            {{- with .Values.volumeMounts.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "sleep 15"
      volumes:
        - name: shared-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "oikotie-scraper.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "oikotie-scraper.fullname" . }}-config
        {{- with .Values.volumes.extra }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}