# Kubernetes secrets for Oikotie Scraper
apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
  namespace: oikotie-scraper
  labels:
    app: oikotie-scraper
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # echo -n "your-webhook-url" | base64
  alert-webhook-url: ""
  # echo -n "your-s3-bucket" | base64
  backup-s3-bucket: ""
  # echo -n "us-east-1" | base64
  backup-s3-region: dXMtZWFzdC0x
  # echo -n "your-access-key" | base64
  aws-access-key-id: ""
  # echo -n "your-secret-key" | base64
  aws-secret-access-key: ""
  # echo -n "admin" | base64
  grafana-admin-password: YWRtaW4=

---
# Service account for scraper pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scraper-service-account
  namespace: oikotie-scraper
  labels:
    app: oikotie-scraper

---
# RBAC for scraper service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: oikotie-scraper
  name: scraper-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scraper-role-binding
  namespace: oikotie-scraper
subjects:
- kind: ServiceAccount
  name: scraper-service-account
  namespace: oikotie-scraper
roleRef:
  kind: Role
  name: scraper-role
  apiGroup: rbac.authorization.k8s.io