# Prometheus configuration for multi-city scraper cluster monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Scraper nodes metrics
  - job_name: 'scraper-nodes'
    static_configs:
      - targets: 
          - 'scraper-node-1:8080'
          - 'scraper-node-2:8080'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [city]
        regex: (.+)
        target_label: city
        replacement: $1

  # City-specific metrics
  - job_name: 'city-metrics'
    static_configs:
      - targets: 
          - 'scraper-node-1:8080'
          - 'scraper-node-2:8080'
    metrics_path: '/metrics/cities'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health check endpoints
  - job_name: 'scraper-health'
    static_configs:
      - targets: 
          - 'scraper-node-1:8080'
          - 'scraper-node-2:8080'
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']